#!/bin/bash

# Gather missing packages
packages=()
if ! command -v fish &>/dev/null; then
  packages+=("fish")
fi
if ! command -v ping &>/dev/null; then
  packages+=("iputils-ping")
fi
if ! command -v dig &>/dev/null; then
  packages+=("dnsutils")
fi

# Install them all at once if needed
if [ ${#packages[@]} -gt 0 ]; then
  sudo apt-get update -y
  sudo apt-get install -y "${packages[@]}"
fi

