#!/bin/bash
if ! command -v fish &> /dev/null
then
  sudo apt-get update -y
  sudo apt-get install -y fish iputils-ping dnsutils
fi

# Only change shell if it's not already fish
if [[ "$SHELL" != *fish* ]]; then
  sudo chsh -s "$(command -v fish)" coder
fi
